---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-home
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.handle }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: {{ .Release.Name }}-home
  resources:
    requests:
      storage: 5Gi

{{/*{{- if .Values.examapi.createStorageClass }}*/}}
{{/*---*/}}
{{/*kind: StorageClass*/}}
{{/*apiVersion: storage.k8s.io/v1*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.examapi.storageClassName }}*/}}
{{/*provisioner: efs.csi.aws.com*/}}
{{/*{{- end }}*/}}
