{{- if .Values.shib.enabled }}
{{- /* [mysql+pymysql,user,password,example.com,3306,database_name] */}}
{{- $dbconnection := regexSplit ":|/|@" .Values.hub.db.url -1  | compact }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub.shib.fullname" . }}-db-password
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  SHIB_ODBC_PASSWORD: {{ index $dbconnection 2 | b64enc | quote }}
{{- end }}

{{ if .Values.shib.sp.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterhub.shib.fullname" . }}-shibd
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  sp-cert.pem: {{ .Values.shib.sp.cert | b64enc | quote }}
  sp-key.pem: {{ .Values.shib.sp.key | b64enc | quote }}
{{- end }}
