{{- if .Values.shib.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.shib.fullname" . }}-shibd
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 1600
    targetPort: 1600
    protocol: TCP
    name: shibd
  selector:
    tier: shibd

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub.shib.fullname" . }}-web
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
#  - port: 80
#    targetPort: 80
#    protocol: TCP
#    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    tier: web
{{- end }}
